version: '3.8'
services:
  nestapp:
    container_name: nestapp
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=postgres
      - PG_USER=myuser
      - PG_PASSWORD=mypassword
      - PG_DB=mydb
      - PG_PORT=5434
      - PG_HOST=postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: my-postgres
    ports:
      - 5434:5434
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - '8080:80'
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: local
