import { AxiosResponse } from '@nestjs/terminus/dist/health-indicator/http/axios.interfaces';
import { EViabilityData } from 'src/core/entity/viability-data/viability-data.entity';
export const RESPONSE_BASIC_DATA_FAILED_HTTP = {
  isAxiosError: true,
  response: {
    data: 'U2FsdGVkX1/aXJ6TD+tz0mK200idKgswBV7lUK5mehBaxTta7AeRmQH9G+rNqbB2zVOPv+ifNn+n1aCW3l/WPuq/cGPEElh5560e2zj5Y/CUu4ChBmYDmkEwwgy68i3t/y2kjscuB83X+WG2pvBaLtjl7G6MhtTBacNwf06+5gCNYJPedBs48R6CBWNwLcfF2bDLwThUaBPJ+EaIjxHOpHyTqCAYyKwHYIFnemWU1WQuhmbv6H01oUu0g0Sm4L4Va2epiKMBXEIAzzQxJWtmh5LJfkaCHLzpOFQcjK/kWtP2D5QfzQ92Cf6pgqXpIOh9YNN91KOtb3IJ5yILHxIg0u6uyGDTH1OJZKD3Ff8v5xXfEQGCa59sDPPTFZ4g6JwZreJV77Dfo/vNMlfj8vUtyYsfYnbwlGqf5zr3E4fRQRHOdFVlzYm4XKbq4ZB3SdB97oPGrZkpUk/kXlDhN4c/b3klfLNz9zya+PNpXS7UuPfZDSQQpWhqssAOYZvdE9p8Q/1R1uP4ZKnmNQuFyn9sCsQLrzi1Cd+eJ/YzMQLKiTOv7aqAI23kB604cR6umXFL64+3EU4/VqAPb42sU1FBvT04Jk1tYdx1Oq/fr6EAJI33k+e+OOrkwVXRX16OjjO/fSLoCGJqI3cXhgUmPsHkJ1qHdybzBv/mAlgJuThCaIoXOjGbAazYu1wcYkoVXR/fzDgOX8S1NOibwCCePGyHPRyKdlhqKve3QAKToxzIYhFhNY7PvJVrtu8ais/wexxA5pP1trLqb5yZ5F/P1BiRei8rNSAs8dEMneXmd00uj7m4pJnoDP3XNIrpfdMSZfPP/1H81+rfwfCH5xmFWv1biUE+UzcvhjKPRomPyKtVc++mSRnaLgsDFm7/xKf9+c7pVEZE2Il30JVjzondFkb4EtIo51EtYyuuqIQdmnDabmg3bDwznuy7mfoTidFweZlk8a0GDpm+Z3bYCnKmYjx+urWOyNQXfNEJMeRaX+OGN0n0parwG9GAA+whxdP369OlPTJpgHIa5vmetVASmdh4x1KGgxs7+LwosM01T/2r6Y4=',
    status: 400,
    statusText: 'OK',
    headers: {},
    config: {},
  },
  config: {
    url: 'valdiate token url',
  },
};

export const RESPONSE_BASIC_DATA_SUCCESS_HTTP = {
  data: 'U2FsdGVkX19P8TfC4t2ikH5w9bewmGp5NZe6RuuR9pz+3fc4QodE7UV9JSAauhHLSVghwPWGo6AMSYSP9xGVkmnCwBXGpAcGgPHPE/b1eW7lPLds0MGJyypWe0fb/BCn6zo6H7PNTIyUBhkQPgqt7Gh/UhFELug0O5MQOKRpdTNoS3WxqJ27I/8WqGlEEN2IZgMlvdQNdz1NbVrTpod3Oj+9ELb3hfOhMJwC7dGaiDPOyldFf3Xljwcy8Os/vsPUiZuCxkBrl4VC66+etcAM34lf0HxLn3u0jglTFEI0zs1MowDpM25g9ZsWBua2Fo2PoQ5dVXQN0syX3mguWkyCt1i7AjmML2X5FbRJOn+oN07Nwbr7zux4/zjJajHRd4dNmC1HLV7/8uYWhFzR6ufbxUUxu5W1REpC5GnN3zpCcf0Qx72ObBrckARUwOo44jSrfpYyrQbbHYOUnSDqZIjwW6YYMR8x0zLtl1wlL1C8rtVNGUIQHdrXb3DGFYzVgOLuzWddD1KCxb8sElvihuhePmhH70v4b9yG7Lzp5sZdqaiekjDuSplnKyP8W5h3flKZnzr4cLK5B2Z7zLFvlXG53Mq7N6eoQJhr4xMYS1u/tmsWbfBUGvbKNebJl9gTanTTmqlEnurgfmd6C2jqX84B/gCmDS0d4acd8/mF4hpcc9R2Mye54UupbsEm2UMiTonQX/XKHdy5D2RnRnoEThSm7TqPkrimhQg/WWi45glx8AbEF3eolwknbP3D6yUg2RDubILxfsRtwC9nF9muK0y8dm1rZNtqQm15MGGHwoOCcd+uE6bm/PPvsNpDkpk3c2W7IFylBylWzfqsytV09oKVlc4ChpNW79Z98vioVCfVtTWVQbHq3fdqV37guuXBlAmNv4V+m/8zWSNhcR3QPhXI4dTuhAlOivOPrqCAGbdlxGj5WS1BfNrFEPK3LCZU+1ML8C58etJaucRFJCLOqzlkEwvYUFe/uFBu9zwV+VEsNezeV/ZRS5vNZePzXIXxsMn+s4/mnIQRQB8HJ3JgIU9lSg0qLifEuav594Ngi9W2pwQQpG2eDQS+IEUs1vsSOcNFErDRzNG4bzBXcVH2A5N/wViZNCIfFYQtYI67SsrQUtDMVLzgkyzVWDYhim3brjWdodKVA1+B2vL/JEiEoHc2ude6dfBFY78IOftX2KzidowFBHXTN5YXnl6L44/Ck1LPD69xCvPjweUMJwF9BygC5EJNeyMNAi0k/TPDUScn3DHu3hJfjo0w/GpZU5s+Bidc+i+NILoyLrykLAwxnPV9YLEo8vwHOulsn4Nyt1ZyqJE1vXSIIlNIlMDijnExpo6GvQeKEOz80Kml77R1pCc4e51LxqYpi/16+4rJ7dh4MS+i1U0bLvdNzMPb9M7uc7IM9HOLDQtHc+hpItXWS0KrkoCps/aR0g/iv3M5DrtTKaXqcZxHkyh7m31X5W1oVQckJJ2Cs+l3ibt0gGOPmLqKiUXxbgDZ0jaibAXA1YY1aWowdDcacJwWlftup/Y+/Jm3pCX56mJblRXKei9DRTinR+o2/F6wtqtnQj5EDkjzcG/t7QJqSm6KhgRD5PS0Hj7CLq2qwvrsZTsY82c9xFHh74mE+2iVpd/NzZcPRqKN5MOwz9DBMrprh71GHbO0haCpOZ+pkb9s/V/JJp7TxXYur+G3a4YC6ycNNROGGnF66xcmXkdiQxBek2ZLoQqKUZqZNWbMZ+NFy2eRqqB7/ph45NbMYLqlXK12LI4/Mbe2/WkVIpvpam108InfWmhugYW9TAWJ2ygIEM7ijX9w4E9ZAo6jyjwda0es+DLhfQPJzEmOuoqgOQK6/JIj35+XuC+bH23LmZ39Neih2BiZ6UT76MSSluj/JijsM9xFjAaj5FffM/NdyW0G2x9FzVIZ2rb/',
  status: 200,
  statusText: 'OK',
  headers: {},
  config: {},
};

export const MOCK_REQUEST_VIBILITY = {
  govIssueIdent: {
    identSerialNum: '32517858',
    govIssueIdentType: 'CC',
  },
  depAcctStmtRec: {
    depAcctId: {
      refId: '1-226396292',
    },
  },
  offer: {
    requestType: 'Sales Order',
    requestVersion: '1',
    viabilityType: 'I',
    processStage: '02',
    cityId: '11001',
    flagRecommended: 'N',
    indMoment: '1.',
    executionLine: 'V',
  },
  applicantInfo: [
    {
      govIssueIdent: {
        identSerialNum: '32517858',
        govIssueIdentType: 'CC',
      },
      personName: {
        lastName: 'ARIAS',
        secondLastName: 'CUSBA',
        firstName: 'ALEJANDRO',
        middleName: 'JUAN',
      },
      personInfo: {
        age: '32',
        maritalStatus: '01',
        educationLevel: '04',
        gender: 'M',
        typeOfHousing: 'O',
      },
      rentalAmt: '0',
      dependantQty: '',
      flagEmployeeFS: 'N',
      fsEmploymentType: '',
      goodCustomer: '',
      flagNoCustomerPresence: '',
      entprBusiness: {
        entprDesc: '',
      },
    },
  ],
  listOcupation: [
    {
      businessInfo: {
        businessType: '03',
        flagMainJobActivity: 'Y',
        formality: 'INFORMAL',
        labourSector: 'PR',
        rentType: '',
        applicantMarket: 'UPNF',
        incomeAmt: '22000000',
        netIncomeAmt: '5800000',
        jobYears: '10',
        jobMonths: '0',
        segment: '18',
        subSegment: 'MICROPEQUE',
        labourContractType: '',
        discountCapacity: 'N',
        flagWorkSite: 'Y',
      },
    },
  ],
  incomeInfo: [
    {
      personInfo: {
        incomeAmt: '22000000',
      },
      idItem: '1-3PQXO8',
      discountCapacity: '',
    },
  ],

  entprBusiness: [
    {
      entprDesc: 'ALMAGRAM',
      postAddr: {
        addr1: '',
      },
      economicSector: '01',
    },
  ],

  entpr: [
    {
      seniority: '10',
      jobYears: '10',
      rentType: '04',
      stateProv: 'CIUDAD SALITRE OCCIDENTAL',
      postAddr: {
        addr1: 'AV CL 26 68 B 70',
        cityId: '11001',
        stateProv: '11000',
        phoneNum: {
          phone: '4589898',
          phoneExt: '',
        },
      },
      latitude: '',
      longitude: '',
      geoStatus: '',
      flagGeoreferenced: '',
      georeferencedDt: '',
      relation: '05',
    },
  ],
  expenses: [
    {
      idItem: '1-3NJHQB',
      amt: '100000',
      suggestedPmtAmt: '200000',
      flagHeadFamily: '02',
      flagFamilyHeritage: '02',
      primaryHome: '02',
      activityWorkSite: '',
      dependantQty: '2',
    },
  ],

  productInfo: [
    {
      itemGeneric1: '1',
      itemGeneric2: '',
      priority: '1',
      productId: {
        ledgerCode: '32',
        subLedgerCode: '01',
        groupCode: '11',
      },
      productClass: '16',
      productType: 'ACTIVO',
      productTA: '320111',
      amtOfferInformed: '150000000.00',
      amtRequested: '70000000',
      curRate: '',
      termUnits: '100',
      entprType: '',
      strategyType: '',
      scvIdent: '',
      strategyId: '',
      campaignId: '',
      exemptionAmt: 'N',
      flagPortfolioBuy: 'N',
      flagRetank: 'N',
      flagIncrementQuota: 'N',
      flagRequiredDual: 'N',
      militaryGrade: '',
      businessType: '',
      businessGradeDetail: '',
      seniorityGradeA: '',
      seniorityGradeM: '',
      extendedDiscount: '',
      othersDiscounts: '',
      productLine: 'CV',
      quotaDiscount: '',
      currentQuota: '0',
      additionalQuota: '0',
      productMaxAmt: '',
      estimateAmt: '',
      amortisationSystem: '',
      flagProductSelected: 'Y',
      flagSelectedOffered: 'S',
      mortagageInfo: {
        changeMortgageCount: '0',
        vlrCtabeneficiaryPG: '',
        registerHousing: '',
        mortgageStatus: '',
        vlrMortgage: '130000000',
        vlrBusinessBuyingSelling: '130000000',
        housingType: '01',
        location: '02',
        cityId: '11001',
        neighborhood: 'SUBA',
        postAddr: {
          addr1: '',
        },
        propertyType: '01',
        socialClass: '3',
        govPrg: '02',
        coverageTermValidity: '84',
        vlrSubsidyFrech: '',
        flagSupGovPrg: '01',
        flagBenGovPrg: '',
        flagHousingVis: '02',
        flagMortgageOtherBank: '',
        flagMotgageBCS: '',
        subRChangeConditionflagReq: '',
        flagFamilyHeritage: '',
        flagContractSigned: '',
        flagAllContractSigned: '',
        flagUpgrading: '',
        flagPropertyPaying: '',
        flagExternalAppraisal: '',
        flagExternalPolicyIRT: '',
        policyType: '',
        opcBuying: '',
        flagPropertyBCS: '',
        flagBLeasing: '',
        leasingType: '',
        operationPerform: '',
        view8020: '',
        savingsCapacity: '21800000',
        savingsObligation: '',
        campaignType: '',
        campaignLimitAmt: '',
        startDt: '',
        endDt: '',
        campaignSellingMonth: '',
        periodOfGrace: '0',
        balanceNominal: '',
        indRenewalUrb: 'N',
        indSubQuota: 'Y',
        idEntitySubQuota: '38',
        indProperty: '01',
        indCTYL: '02',
        obligationNum: '',
      },
      obligationNum: {
        flagGuaranteeBCS: '',
        flagLoanCollection: '',
        flagRateOhterEntity: '',
        resourcesType: '',
        destProdOwnResouces: '',
        creditLineBancoldex: '',
        invesmentBancoldex: '',
        guaranteeRequired: '',
        finalGuarantee: '',
        paymentFNGType: '',
        vlrFNGCommission: '',
        fngProductCod: '',
        lineNameBancoldex: '',
        lineDestinyBancoldex: '',
        flagFNG: 'N',
        aproxAmtFNG: '0',
        vlrRentingMortagage: '0',
        guaranteeProcessConst: '',
        cityMV: '',
        socialClassMV: '',
        flagRequiredUpdateAppraisal: '',
        amtRequestedOrigin: '',
        termOrderOrigin: '',
        systemAmortOrderOrigin: '',
        vlrInmbOrderOrigin: '',
      },
      payPeriodicityId: '01',
    },
  ],
  relationtInfo: [
    {
      govIssueIdent: {
        identSerialNum: '32517858',
        govIssueIdentType: 'CC',
      },
      personName: {
        lastName: 'ARIAS',
        secondLastName: 'CUSBA',
        firstName: 'ALEJANDRO',
        middleName: 'JUAN',
      },
      relationType: '01',
      relationShipPpal: '',
      flagIndInsurable: 'Y',
      flagContributorING: 'S',
      flagReqSignedContract: 'N',
      flagPolicyExtremeHousing: 'N',
    },
  ],
  listOrigPropertyData: [
    {
      idItem: '1-3QSGIQ',
      projectCode: '192160001975',
      unitCode: '',
      projectType: '01',
      nitBuilder: '8300558977',
      nameBuilder: 'PATRIMONIOS AUTONOMOS FIDUCIAR',
      nameProject: 'CIUDAD VERDE CIPRES',
      unit: '',
      postAddr: {
        addr1: '',
        addr2: 'SUPER MANZANA 45 LOTE 3 ET. 7A CIUDAD VERDE',
      },
      unitStatus: '',
      flagEscrow: 'N',
    },
  ],
};

export const MOCK_RESPONSE_VIABILITY = {
  govIssueIdent: {
    identSerialNum: '32517858',
    govIssueIdentType: 'CC',
  },
  depAcctStmtRec: {
    depAcctId: {
      refNumber: '1-226396292',
    },
  },
  offer: {
    requestType: 'Sales Order',
    requestVersion: '1',
    viabilityResult: '02',
    creditRating: 'A',
    creditProfile: null,
    flagException: 'N',
    flagBuroQuery: 'N',
    scoreType: '07',
    score: '717',
    dataCreditBuroPriority: 'N',
    cifinBuroPriority: 'Y',
    flagHypoBalancedOffer: 'Y',
    indMoment: '1.',
    executionLine: 'V',
    requestFastenAdjust: null,
    riskLevel: null,
  },
  aplicantInfo: [
    {
      govIssueIdent: {
        govIssueIdentType: 'CC',
        identSerialNum: '98528543',
      },
      goodCustomer: 'NO',
    },
    {
      govIssueIdent: {
        govIssueIdentType: 'CC',
        identSerialNum: '1110176019',
      },
      goodCustomer: 'NO',
    },
  ],
  indebtedness: null,
  listCausalExceptionInfo: null,
  listNoViabilityInfo: null,
  productInfo: [
    {
      itemGeneric1: '1101',
      itemGeneric2: '1101',
      productId: {
        ledgerCode: null,
        subLedgerCode: null,
        groupCode: null,
      },
      amtOfferInformed: '150000000.00',
      curRate: '15.15',
      termUnits: '100.0',
      entprType: null,
      strategyType: null,
      scvIdent: null,
      strategyId: null,
      resultViabilityProductInformed: 'Y',
      flagPortfolioBuy: null,
      bussinesActivity: {
        militaryGrade: null,
        businessType: null,
        businessGradeDetail: null,
        seniorityGradeA: null,
        seniorityGradeM: null,
      },
      currentQuota: null,
      additionalQuota: null,
      productMaxAmt: null,
      estimateAmt: '2563020.91',
      vlrExcess: null,
      amortisationSystem: '01',
      vlrInitialQuota: null,
      benefitPG: null,
      periodOfGrace: '0',
      flagProductSelected: null,
      flagSelectedOffered: null,
      mortagageInfo: {
        changeMortgageCount: null,
        registerHousing: null,
        mortgageStatus: null,
        vlrMortagage: '130000000',
        vlrBusinessBuyingSelling: '130000000',
        housingType: '01',
        location: '02',
        cityId: '11001',
        neighborhood: 'SUBA',
        postAddr: {
          addr1: null,
        },
        propertyType: '01',
        socialClass: '3',
        govPrg: '02',
        coverageTermValidity: '84',
        vlrSubsidyFrech: null,
        rateFull: null,
        adjustmentCP: null,
        flagSupGovPrg: null,
        flagBenGovPrg: null,
        flagHousingVis: '02',
        flagMortgageOtherBank: null,
        flagMotgageBCS: null,
        subRChangeConditionflagReq: null,
        flagFamilyHeritage: null,
        flagContractSigned: null,
        flagAllContractSigned: null,
        flagUpgrading: null,
        flagPropertyPaying: null,
        flagExternalAppraisal: null,
        flagExternalPolicyIRT: null,
        policyType: null,
        flagPropertyBCS: null,
        flagBLeasing: null,
        leasingType: null,
        opcBuying: null,
        operationPerform: null,
        view8020: null,
        termSuggestedMinimun: '99.0',
        ownResourcesInitialFee: '1.5E8',
        flagFNG: null,
        quotaFrech: '0.00',
        balanceNominal: null,
        indRenewalUrb: 'N',
        indSubQuota: 'Y',
        idEntitySubQuota: '38',
        rateWithBenefit: '0',
        indProperty: '01',
        indCTYL: '02',
        obligationNum: null,
        flagGuaranteeBCS: null,
      },
      obligationNum: {
        resourcesType: null,
        destProdOwnResouces: null,
        creditLineBancoldex: null,
        invesmentBancoldex: null,
        commissionMyPymeIva: null,
        commissionUsaidIva: null,
        guaranteeRequired: null,
        finalGuarantee: null,
        paymentFNGType: null,
        vlrFNGCommission: null,
        commissionMyPymeWithoutIva: null,
        commissionUsaidWithoutIva: null,
        vlrFNGCommissionWithoutIva: null,
        factorMyPyme: null,
        factorUsaid: null,
        factorFNG: null,
        fNGproductCod: null,
        lineNameBancoldex: null,
        lineDestinyBancoldex: null,
        aproxAmtFNG: null,
        vlrRentingMortagage: null,
        initialRate: null,
        initialTypeRate: null,
        guaranteeProcessConst: null,
        cityMV: null,
        socialClassMV: null,
        flagRequiredUpdateAppraisal: null,
        amtRequestedOrigin: null,
        termOrderOrigin: null,
        systemAmortOrderOrigin: null,
        vlrInmbOrderOrigin: null,
      },
      payPeriodicityId: '01',
    },
    {
      itemGeneric1: '1102',
      itemGeneric2: '1102',
      productId: {
        ledgerCode: null,
        subLedgerCode: null,
        groupCode: null,
      },
      amtOfferInformed: '118214032.00',
      curRate: '15.15',
      termUnits: '100.0',
      entprType: null,
      strategyType: null,
      scvIdent: null,
      strategyId: null,
      resultViabilityProductInformed: 'Y',
      flagPortfolioBuy: null,
      bussinesActivity: {
        militaryGrade: null,
        businessType: null,
        businessGradeDetail: null,
        seniorityGradeA: null,
        seniorityGradeM: null,
      },
      currentQuota: null,
      additionalQuota: null,
      productMaxAmt: null,
      estimateAmt: '2579999.99',
      vlrExcess: null,
      amortisationSystem: '02',
      vlrInitialQuota: null,
      benefitPG: null,
      periodOfGrace: '0',
      flagProductSelected: 'N',
      flagSelectedOffered: 'A',
      mortagageInfo: {
        changeMortgageCount: null,
        registerHousing: null,
        mortgageStatus: null,
        vlrMortagage: '130000000',
        vlrBusinessBuyingSelling: '130000000',
        housingType: '01',
        location: '02',
        cityId: '11001',
        neighborhood: 'SUBA',
        postAddr: {
          addr1: null,
        },
        propertyType: '01',
        socialClass: '3',
        govPrg: '02',
        coverageTermValidity: '84',
        vlrSubsidyFrech: null,
        rateFull: null,
        adjustmentCP: null,
        flagSupGovPrg: null,
        flagBenGovPrg: null,
        flagHousingVis: '02',
        flagMortgageOtherBank: null,
        flagMotgageBCS: null,
        subRChangeConditionflagReq: null,
        flagFamilyHeritage: null,
        flagContractSigned: null,
        flagAllContractSigned: null,
        flagUpgrading: null,
        flagPropertyPaying: null,
        flagExternalAppraisal: null,
        flagExternalPolicyIRT: null,
        policyType: null,
        flagPropertyBCS: null,
        flagBLeasing: null,
        leasingType: null,
        opcBuying: null,
        operationPerform: null,
        view8020: null,
        termSuggestedMinimun: '120.0',
        ownResourcesInitialFee: '1.81785968E8',
        flagFNG: null,
        quotaFrech: '0.00',
        balanceNominal: null,
        indRenewalUrb: 'N',
        indSubQuota: 'Y',
        idEntitySubQuota: '38',
        rateWithBenefit: '0',
        indProperty: '01',
        indCTYL: '02',
        obligationNum: null,
        flagGuaranteeBCS: null,
      },
      obligationNum: {
        resourcesType: null,
        destProdOwnResouces: null,
        creditLineBancoldex: null,
        invesmentBancoldex: null,
        commissionMyPymeIva: null,
        commissionUsaidIva: null,
        guaranteeRequired: null,
        finalGuarantee: null,
        paymentFNGType: null,
        vlrFNGCommission: null,
        commissionMyPymeWithoutIva: null,
        commissionUsaidWithoutIva: null,
        vlrFNGCommissionWithoutIva: null,
        factorMyPyme: null,
        factorUsaid: null,
        factorFNG: null,
        fNGproductCod: null,
        lineNameBancoldex: null,
        lineDestinyBancoldex: null,
        aproxAmtFNG: null,
        vlrRentingMortagage: null,
        initialRate: null,
        initialTypeRate: null,
        guaranteeProcessConst: null,
        cityMV: null,
        socialClassMV: null,
        flagRequiredUpdateAppraisal: null,
        amtRequestedOrigin: null,
        termOrderOrigin: null,
        systemAmortOrderOrigin: null,
        vlrInmbOrderOrigin: null,
      },
      payPeriodicityId: '01',
    },
    {
      itemGeneric1: '1103',
      itemGeneric2: '1103',
      productId: {
        ledgerCode: null,
        subLedgerCode: null,
        groupCode: null,
      },
      amtOfferInformed: '150000000.00',
      curRate: '8.1',
      termUnits: '100.0',
      entprType: null,
      strategyType: null,
      scvIdent: null,
      strategyId: null,
      resultViabilityProductInformed: 'Y',
      flagPortfolioBuy: null,
      bussinesActivity: {
        militaryGrade: null,
        businessType: null,
        businessGradeDetail: null,
        seniorityGradeA: null,
        seniorityGradeM: null,
      },
      currentQuota: null,
      additionalQuota: null,
      productMaxAmt: null,
      estimateAmt: '2052209.46',
      vlrExcess: null,
      amortisationSystem: '03',
      vlrInitialQuota: null,
      benefitPG: null,
      periodOfGrace: '0',
      flagProductSelected: 'N',
      flagSelectedOffered: 'A',
      mortagageInfo: {
        changeMortgageCount: null,
        registerHousing: null,
        mortgageStatus: null,
        vlrMortagage: '130000000',
        vlrBusinessBuyingSelling: '130000000',
        housingType: '01',
        location: '02',
        cityId: '11001',
        neighborhood: 'SUBA',
        postAddr: {
          addr1: null,
        },
        propertyType: '01',
        socialClass: '3',
        govPrg: '02',
        coverageTermValidity: '84',
        vlrSubsidyFrech: null,
        rateFull: null,
        adjustmentCP: null,
        flagSupGovPrg: null,
        flagBenGovPrg: null,
        flagHousingVis: '02',
        flagMortgageOtherBank: null,
        flagMotgageBCS: null,
        subRChangeConditionflagReq: null,
        flagFamilyHeritage: null,
        flagContractSigned: null,
        flagAllContractSigned: null,
        flagUpgrading: null,
        flagPropertyPaying: null,
        flagExternalAppraisal: null,
        flagExternalPolicyIRT: null,
        policyType: null,
        flagPropertyBCS: null,
        flagBLeasing: null,
        leasingType: null,
        opcBuying: null,
        operationPerform: null,
        view8020: null,
        termSuggestedMinimun: '92.0',
        ownResourcesInitialFee: '1.5E8',
        flagFNG: null,
        quotaFrech: '0.00',
        balanceNominal: null,
        indRenewalUrb: 'N',
        indSubQuota: 'Y',
        idEntitySubQuota: '38',
        rateWithBenefit: '0',
        indProperty: '01',
        indCTYL: '02',
        obligationNum: null,
        flagGuaranteeBCS: null,
      },
      obligationNum: {
        resourcesType: null,
        destProdOwnResouces: null,
        creditLineBancoldex: null,
        invesmentBancoldex: null,
        commissionMyPymeIva: null,
        commissionUsaidIva: null,
        guaranteeRequired: null,
        finalGuarantee: null,
        paymentFNGType: null,
        vlrFNGCommission: null,
        commissionMyPymeWithoutIva: null,
        commissionUsaidWithoutIva: null,
        vlrFNGCommissionWithoutIva: null,
        factorMyPyme: null,
        factorUsaid: null,
        factorFNG: null,
        fNGproductCod: null,
        lineNameBancoldex: null,
        lineDestinyBancoldex: null,
        aproxAmtFNG: null,
        vlrRentingMortagage: null,
        initialRate: null,
        initialTypeRate: null,
        guaranteeProcessConst: null,
        cityMV: null,
        socialClassMV: null,
        flagRequiredUpdateAppraisal: null,
        amtRequestedOrigin: null,
        termOrderOrigin: null,
        systemAmortOrderOrigin: null,
        vlrInmbOrderOrigin: null,
      },
      payPeriodicityId: '01',
    },
    {
      itemGeneric1: '1104',
      itemGeneric2: '1104',
      productId: {
        ledgerCode: null,
        subLedgerCode: null,
        groupCode: null,
      },
      amtOfferInformed: '131451536.00',
      curRate: '8.1',
      termUnits: '100.0',
      entprType: null,
      strategyType: null,
      scvIdent: null,
      strategyId: null,
      resultViabilityProductInformed: 'Y',
      flagPortfolioBuy: null,
      bussinesActivity: {
        militaryGrade: null,
        businessType: null,
        businessGradeDetail: null,
        seniorityGradeA: null,
        seniorityGradeM: null,
      },
      currentQuota: null,
      additionalQuota: null,
      productMaxAmt: null,
      estimateAmt: '2176972.89',
      vlrExcess: null,
      amortisationSystem: '04',
      vlrInitialQuota: null,
      benefitPG: null,
      periodOfGrace: '0',
      flagProductSelected: 'N',
      flagSelectedOffered: 'A',
      mortagageInfo: {
        changeMortgageCount: null,
        registerHousing: null,
        mortgageStatus: null,
        vlrMortagage: '130000000',
        vlrBusinessBuyingSelling: '130000000',
        housingType: '01',
        location: '02',
        cityId: '11001',
        neighborhood: 'SUBA',
        postAddr: {
          addr1: null,
        },
        propertyType: '01',
        socialClass: '3',
        govPrg: '02',
        coverageTermValidity: '84',
        vlrSubsidyFrech: null,
        rateFull: null,
        adjustmentCP: null,
        flagSupGovPrg: null,
        flagBenGovPrg: null,
        flagHousingVis: '02',
        flagMortgageOtherBank: null,
        flagMotgageBCS: null,
        subRChangeConditionflagReq: null,
        flagFamilyHeritage: null,
        flagContractSigned: null,
        flagAllContractSigned: null,
        flagUpgrading: null,
        flagPropertyPaying: null,
        flagExternalAppraisal: null,
        flagExternalPolicyIRT: null,
        policyType: null,
        flagPropertyBCS: null,
        flagBLeasing: null,
        leasingType: null,
        opcBuying: null,
        operationPerform: null,
        view8020: null,
        termSuggestedMinimun: '120.0',
        ownResourcesInitialFee: '1.68548464E8',
        flagFNG: null,
        quotaFrech: '0.00',
        balanceNominal: null,
        indRenewalUrb: 'N',
        indSubQuota: 'Y',
        idEntitySubQuota: '38',
        rateWithBenefit: '0',
        indProperty: '01',
        indCTYL: '02',
        obligationNum: null,
        flagGuaranteeBCS: null,
      },
      obligationNum: {
        resourcesType: null,
        destProdOwnResouces: null,
        creditLineBancoldex: null,
        invesmentBancoldex: null,
        commissionMyPymeIva: null,
        commissionUsaidIva: null,
        guaranteeRequired: null,
        finalGuarantee: null,
        paymentFNGType: null,
        vlrFNGCommission: null,
        commissionMyPymeWithoutIva: null,
        commissionUsaidWithoutIva: null,
        vlrFNGCommissionWithoutIva: null,
        factorMyPyme: null,
        factorUsaid: null,
        factorFNG: null,
        fNGproductCod: null,
        lineNameBancoldex: null,
        lineDestinyBancoldex: null,
        aproxAmtFNG: null,
        vlrRentingMortagage: null,
        initialRate: null,
        initialTypeRate: null,
        guaranteeProcessConst: null,
        cityMV: null,
        socialClassMV: null,
        flagRequiredUpdateAppraisal: null,
        amtRequestedOrigin: null,
        termOrderOrigin: null,
        systemAmortOrderOrigin: null,
        vlrInmbOrderOrigin: null,
      },
      payPeriodicityId: '01',
    },
  ],
  relationtInfo: null,
  listNoViabilityRelationInfo: null,
  listExceptionRelationInfo: null,
  listObligation: null,
  listRetankCollectBalance: null,
  listOrigPropertyData: [
    {
      idItem: '1-3QSGIQ',
      projectCode: '192160001975',
      unitCode: null,
      projectType: '01',
      nitBuilder: '8300558977',
      nameBuilder: 'PATRIMONIOS AUTONOMOS FIDUCIAR',
      nameProject: 'CIUDAD VERDE CIPRES',
      unit: null,
      postAddr: {
        addr1: null,
        addr2: 'SUPER MANZANA 45 LOTE 3 ET. 7A CIUDAD VERDE',
      },
      unitStatus: null,
      flagEscrow: null,
    },
  ],
  listDataCurrentGuarantee: null,
  listDataCreditHolder: null,
  listMortagageCredit: null,
};
export const SUCCESS_VIABILITY_RESPONSE: AxiosResponse = {
  data: MOCK_RESPONSE_VIABILITY,
  status: 200,
  statusText: 'OK',
  headers: {},
  config: {},
};

export const TOKEN_ERROR_VIABILITY_RESPONSE = {
  isAxiosError: true,
  response: {
    data: {
      error: 'Token has expired.',
    },
    status: 401,
    statusText: 'OK',
    headers: {},
    config: {},
  },
  config: {
    url: 'valdiate token url',
  },
};

export const ERROR_VIABILITY_RESPONSE_400: AxiosResponse = {
  data: {
    ResponseType: {
      value: 'ER',
    },
    ResponseDetail: {
      ErrorCode: '13000',
      ErrorDesc:
        'No existe en BD datos de TyC para este cliente, ruta  en TENENCIACOMPORTAMIENTO Cliente: CC46373008',
      ErrorType: 'RGN',
    },
  },
  status: 400,
  statusText: 'OK',
  headers: {},
  config: {},
};

export const CONTACT_DATA = {
  customerKey: 'h124',
  processId: '23',
  microService: 'Servicio',
  activity: 'Save contact data',
  ip: '192.168.0.130',
  city: 'Bogota',
  phoneNumber: '3138726824',
  totalMonthlyIncome: 2,
  totalDiscountsHealth: 8,
  totalOtherVoucherDiscounts: 7,
  branchOffice: '11011',
};

export const SUCCESSFUL_API_BASIC_DATA = {
  data: {
    govIssueIdent: {
      identSerialNum: '1013605126',
      govIssueIdentType: 'CC',
    },
    personInfo: {
      age: '33',
      birthDt: '06/12/1989',
      typeOfHousing: null,
      educationLevel: '04',
      gender: 'M',
      maritalStatus: '01',
      govIssueIdent: {
        expDt: '06/22/2007',
      },
      deceaseCert: null,
      deceaseDt: null,
    },
    contactInfo: {
      emailAddr: 'prueba3@fs.net',
      phoneNum: {
        cellPhone: '3600000006',
      },
    },
    businessActivity: {
      businessGrade: null,
      startInabilityDt: null,
      endInabilityDt: null,
    },
    postAddr: {
      startDt: '12 años 4 meses',
    },
    fsEmploymentType: null,
    rentalAmt: null,
    dependantQty: null,
    personName: {
      lastName: 'OYUELA',
      secondLastName: 'MUJICA',
      firstName: 'LEONILA',
      middleName: 'EDIXON',
      fullName: 'LEONILA EDIXON OYUELA MUJICA',
    },
    entpr: {
      entprDesc: null,
    },
    applicantInfo: {
      sarlaftDate: null,
    },
    ocupationInfoList: [
      {
        businessInfo: {
          businessType: null,
          flagMainJobActivity: null,
          formality: null,
          labourSector: '',
          rentType: null,
          applicantMarket: null,
          incomeAmt: null,
          netIncomeAmt: null,
          jobYears: null,
          jobMonths: null,
          segment: null,
          subSegment: null,
          labourContractType: '',
          discountCapacity: 'N',
          flagWorkSite: 'Y',
        },
      },
    ],
    listIncomeReferenceJob: null,
    listAddress: [
      {
        postAddr: {
          cityId: '25843',
          neighborhood: 'PRADO CENTRO',
        },
        phoneNum: {
          phoneExt: null,
          phoneAreaCode: '11001',
          phone: '1000000',
        },
        relationType: '01',
        applicantInfo: {
          leafletType: 'Customer',
        },
      },
      {
        postAddr: {
          cityId: '73563',
          neighborhood: 'EMAYA',
        },
        phoneNum: {
          phoneExt: null,
          phoneAreaCode: '11001',
          phone: '3000002',
        },
        relationType: '04',
        applicantInfo: {
          leafletType: 'Customer',
        },
      },
      {
        postAddr: {
          cityId: '25286',
          neighborhood: 'RESTREPO',
        },
        phoneNum: {
          phoneExt: null,
          phoneAreaCode: '11001',
          phone: '2000001',
        },
        relationType: '03',
        applicantInfo: {
          leafletType: 'Customer',
        },
      },
    ],
  },
  status: 200,
  statusText: 'OK',
  headers: {},
  config: {},
};

export const VIABILITY_DATA = {
  responseNotification: null,
  offerSendToClient: true,
  secondRequest: true,
  offerDeliveredToBussiness: false,
  documentNumber: 1111111, //tipo de documento
  documentType: 'CC', //número de documento
  names: 'Pepito Alberto', //nombres
  lastNames: 'Casas Altas', //apellidos
  loanAgreement: 'string', //convenio
  loanAgreementDescription: 'string', //nombre de convenio
  amountPrebid: 12500000, //monto preofertado
  duration: 50, // plazo
  rateEA: 14.2, // tasa(E.A)
  rateMV: 2.5, // tasa(M.V)
  estimatedQuota: 4500000, // Cuota estimada
  totalMonthlyIncome: 2500000, // Ingresos mensuales por pensión
  totalDiscountsHealth: 150000, // Descuento por salud
  totalOtherVoucherDiscounts: 230000, //Total otros descuentos
  cityOfResidence: '11001', //ciudad de residencia
  phoneNumber: '311452145', //número de celular
  responseViability: JSON.stringify(MOCK_REQUEST_VIBILITY), //respuesta de api musesolf
  branchOffice: '110001',
  updateAt: '12/10/2022',
  ammountInsurance: 150.0,
  documentNumberBankAdviser: '545454',
} satisfies EViabilityData;

export const VIABILITY_GET = [
  {
    responseNotification: null,
    offerDeliveredToBussiness: false,
    offerSendToClient: true,
    secondRequest: true,
    documentNumber: 1111111,
    documentType: 'CC',
    names: "'Pepito Alberto'",
    lastNames: '   Casas Altas     ',
    loanAgreement: 'string',
    loanAgreementDescription: '  string   ',
    amountPrebid: 12500000,
    duration: 50,
    rateEA: 14.2,
    rateMV: 2.5,
    estimatedQuota: 4500000,
    totalMonthlyIncome: 2500000,
    totalDiscountsHealth: 150000,
    totalOtherVoucherDiscounts: 230000,
    cityOfResidence: '11001',
    phoneNumber: '311452145',
    branchOffice: '110001',
    createdAt: '2023-04-12T16:57:54.632Z',
    updatedAt: '2023-04-12T16:57:54.632Z',
    documentNumberBankAdviser: '545454',
  },
];

export const VIABILITY_DATA_UPDATE = {
  offerSendToClient: true,
  secondRequest: true,
  offerDeliveredToBussiness: false,
  documentNumber: 109884890, //número de documento
  documentType: 'CC', //tipo de documento
  names: 'Pepito Alberto', //nombres
  lastNames: 'Casas Altas', //apellidos
  loanAgreement: 'string', //convenio
  amountPrebid: 15000000, //monto preofertado
  duration: 65, // plazo
  rateEA: 14.2, // tasa(E.A)
  rateMV: 2.5, // tasa(M.V)
  estimatedQuota: 8500000, // Cuota estimada
  totalMonthlyIncome: 2500000, // Ingresos mensuales por pensión
  totalDiscountsHealth: 150000, // Descuento por salud
  totalOtherVoucherDiscounts: 230000, //Total otros descuentos
  cityOfResidence: 'Bogotá', //ciudad de residencia
  phoneNumber: '311452145', //número de celular
  responseViability: JSON.stringify(MOCK_REQUEST_VIBILITY), //respuesta de api musesolf
  responseNotification: 'response', // respeusta del api de notificaciones
  branchOffice: '11011',
  ammountInsurance: 150.0,
  documentNumberBankAdviser: '545454',
  loanAgreementDescription: 'dfdfdf',
} satisfies EViabilityData;

export const VIABILITY_DATA_SENT = {
  offerSendToClient: true,
  secondRequest: true,
  offerDeliveredToBussiness: true,
  documentNumber: 109884890, //tipo de documento
  documentType: 'CC', //número de documento
  names: 'Pepito Alberto', //nombres
  lastNames: 'Casas Altas', //apellidos
  loanAgreement: 'string', //convenio
  amountPrebid: 15000000, //monto preofertado
  duration: 65, // plazo
  rateEA: 14.2, // tasa(E.A)
  rateMV: 2.5, // tasa(M.V)
  estimatedQuota: 8500000, // Cuota estimada
  totalMonthlyIncome: 2500000, // Ingresos mensuales por pensión
  totalDiscountsHealth: 150000, // Descuento por salud
  totalOtherVoucherDiscounts: 230000, //Total otros descuentos
  cityOfResidence: 'Bogotá', //ciudad de residencia
  phoneNumber: '311452145', //número de celular
  responseViability: JSON.stringify(MOCK_REQUEST_VIBILITY), //respuesta de api musesolf
  responseNotification: 'response', // respeusta del api de notificaciones
  branchOffice: '11011',
  loanAgreementDescription: 'dfdfdf',
  ammountInsurance: 150.0,
  documentNumberBankAdviser: '',
} satisfies EViabilityData;

export const LOAN_AGREEMENT_CACHE = {
  govIssueIdent: {
    identSerialNum: '1234567890',
    govIssueIdentType: 'CC',
  },
  depAcctStmtRec: {
    depAcctId: {
      acctId: '550100000000001',
    },
  },
  disbursement: {
    amt: '1',
    quota: '1',
    rate: '1',
    status: '02',
    statusDate: '2012-02-29T11:02:56.000-05:00',
    agreementNumber: '10001420',
  },
  indebtedness: {
    term: '1',
  },
  cardAcctId: {
    numAsignInstallments: '1',
  },
  expenses: {
    suggestedPmtAmt: '1',
  },
  loanInfoCommon: {
    completedPmtCount: '1',
    lastPmtDt: '1',
  },
  product: {
    productType: 'ACTIVO',
    productId: 'ACTIVO',
  },
  entprAgreement: {
    entprDesc: '',
  },
};

export const RATES_AGREEMENT_RESPONSE_SUCCESSFUL = {
  productInfo: [
    {
      productId: {
        legerCode: '30',
        subLegerCode: '01',
        groupCode: '21',
      },
      productLine: '1',
      rate: '22.9',
      bestRate: '22.9',
      factorDiscountGovernmentPlan: '',
      amortisationSystem: '1',
    },
  ],
  entpr: [
    {
      entprId: '1',
      strategyId: '1',
    },
  ],
};

export const RATES_AGREEMENT_REQUEST = {
  productInfo: {
    productId: {
      legerCode: '30',
      subLegerCode: '01',
      groupCode: '21',
    },
    amt: '50000000',
    term: '60',
    rangeFM: '1',
    profile: 'A',
    productLine: '1',
    amortisationSystem: '1',
    score: '1',
  },
  mortagageInfo: {
    govPrg: '1',
    flagHousingVis: '1',
    propertyType: '1',
    flagHousing: '1',
    vlrAppraisal: '1',
    opcBuying: '1',
    indRenewalUrb: '1',
    indHousing: '1',
    flagExternalAppraisal: '1',
    flagFNG: 'Y',
    lineCreditGuarantorEntities: '1',
    fngProductCod: '11',
    guaranteeType: '1',
  },
  entpr: {
    entprId: '1',
    estrategyId: '1',
  },
  campaign: {
    campaignId: '1',
  },
  offer: {
    executionLine: 'C',
    processStage: '1',
  },
  projectData: {
    projectType: '1',
    builderType: '1',
  },
  indebtedness: {
    flagSessionPortfolio: 'Y',
  },
  bussinesInfo: {
    segment: '1',
    flagOldClient: 'Y',
    flagEmployeeFS: 'Y',
  },
  personInfo: {
    incomeAmt: '1',
  },
};

export const SUCCESS_RATES_RESPONSE: AxiosResponse = {
  data: RATES_AGREEMENT_RESPONSE_SUCCESSFUL,
  status: 200,
  statusText: 'OK',
  headers: {},
  config: {},
};

export const ERROR_RATES_RESPONSE_400: AxiosResponse = {
  data: {
    responseType: {
      value: 'ER',
    },
    responseDetail: {
      errorCode: '00001',
      errorDesc: 'Error En Consultar Tasas',
      errorType: 'ER',
    },
  },

  status: 400,
  statusText: 'OK',
  headers: {},
  config: {},
};

export const MOCK_DTO_RESPONSE_BODY_DATA_VIABILITY = {
  responseNotification: null,
  offerSendToClient: false,
  offerDeliveredToBussiness: false,
  secondRequest: true,
  documentNumber: 93355310,
  documentType: 'CC',
  names: 'HENRYARLEY',
  lastNames: 'GUZMANTORRES',
  loanAgreement: '10000334',
  amountPrebid: 2563020.91,
  duration: 100,
  rateEA: 15.15,
  rateMV: 1.1824820244950685,
  estimatedQuota: 2563020.91,
  totalMonthlyIncome: 2,
  totalDiscountsHealth: 8,
  totalOtherVoucherDiscounts: 7,
  cityOfResidence: 'Armenia',
  phoneNumber: '2141789902',
  createdAt: '2023-02-20T19:52:10.261Z',
  updatedAt: '2023-02-20T22:56:46.821Z',
};
