process.env.PORT = 3000;
process.env.ENCRYPTKEY = 'OCRENCRYPTKEY';
process.env.ENCRYPTMULESOFTKEY = 'B@ncoC@j@Soci@l';
process.env.ENCRYPT_MULESOFT_KEY = 'ccs';
process.env.APIOAUTHCLIENTID = 'client_id*****';
process.env.APIOAUTHCLIENTSECRET = 'client-sercret******';
process.env.APIOAUTHURL = 'https://token-service.com';
process.env.PAYROLLLOANVALIDATEUSERURL = 'http://validate-service.com';
process.env.PAYROLLLOANVALIDATEUSERCLIENTSECRET = 'client_id******';
process.env.PAYROLLLOANVALIDATEUSERCLIENTID = 'client-sercret******';
process.env.PAYROLLAUTHVALIDATEAPIKYCALLOWLIST =
  'https://bancocajasocialsa.com';
process.env.PAYROLLAUTHVALIDATEKEYKYCALLOWLIST =
  'AAAAB3NzaC1yc2EAAAADAQABAAABAQDXOfKT0V/NqRsmJCRBG0AYp+OZpc2Dd1U2OI2ohEudi86tSH5OqEcnNtAaF80ya6D8S8DicYXEKM7Rrku/q3c79HLD37BDfC6TQNkDlu9AfUf20aMZtwCZHzuforsLhaV9qXWD+wwbul08d3VrSPCIXHuvNYCMXGP3ttGQSi7S8LBlwM5blhu7WLju0gcCtatJpGNSXUvNOhMssiMm9VN98JFBNNW4PC7zSOWomVkmMXekAEHcZ3qkqO0031IoiliSCfldqCX7qOxCAo3MxE/jrxSYrf0d3sevVlMzPcUiHTLvAVrPiuPlX0cYJMd4w1f0tKrYzNE8aFrSS7lEhfHX';
process.env.PAYROLLCUSTOMERCORECONSOLIDATEDPROFILEURL =
  'https://perfilconsolidado.com';
process.env.PAYROLLCUSTOMERAPICLIENTIDCONSOLIDATEDPROFILE = 'client_id******';
process.env.PAYROLLCUSTOMERAPICLIENTSECRETCONSOLIDATEDPROFILE =
  'client-sercret******';
process.env.PAYROLLCUSTOMERCOREPRODUCTDETAILURL = 'https://detalleproducto.com';
process.env.PAYROLLCUSTOMERAPICLIENTIDPRODUCTDETAIL = 'client_id******';
process.env.PAYROLLCUSTOMERAPICLIENTSECRETPRODUCTDETAIL =
  'client-sercret******';
process.env.PAYROLLCUSTOMERTTL = 86400;
process.env.PAYROLLLOANJWTSECRET = 'banco@Caja@Social';
process.env.APISBCSPEM = 'PEM DEL SSL';
process.env.APISBCSCERT = 'CERT DEL SSL';
process.env.APISBCSKEY = 'KEY DEL SSL';
process.env.APISBCSAVAILABLE = 'true';
process.env.PAYROLLCUSTOMERCOREBLACKLISTMANAGEMENTURL = 'https://tenencia.com';
process.env.PAYROLLCUSTOMERAPICLIENTIDBLACKLISTMANAGEMENT = 'client_id******';
process.env.PAYROLLCUSTOMERAPICLIENTSECRETBLACKLISTMANAGEMENT =
  'client-sercret******';
process.env.PAYROLLSIMULATORLOANAGREEMENTTTL = 86400;
process.env.REDISKEY = 'REDISKEY';
process.env.REDISURL = 'REDISURL';
process.env.REDISPORT = 'REDISPORT';
process.env.REDISTTL = 'REDISTTL';
process.env.APIEXEMPTIONDOCUMENTURL = 'APIEXEMPTIONDOCUMENTURL';
process.env.APIEMPTIONDOCUMENTCLIENTID = 'APIEMPTIONDOCUMENTCLIENTID';
process.env.APIEMPTIONDOCUMENTCLIENTSECRET = 'APIEMPTIONDOCUMENTCLIENTSECRET';
process.env.APIGENERATEDOCSUMENTURL = 'APIGENERATEDOCSUMENTURL';
process.env.APIGENERATEDOCSCLIENTID = 'APIGENERATEDOCSCLIENTID';
process.env.APIGENERATEDOCSCLIENTSECRET = 'APIGENERATEDOCSCLIENTSECRET';
process.env.APIDOCUMENTRULESUMENTURL = 'APIDOCUMENTRULESUMENTURL';
process.env.APIDOCUMENTRULECLIENTID = 'APIDOCUMENTRULECLIENTID';
process.env.APIDOCUMENTRULECLIENTSECRET = 'APIDOCUMENTRULECLIENTSECRET';
process.env.PAYROLLJWTDURATION = '1h';
process.env.PAYROLLLOANCORSORIGIN =
  'http://localhost:8080,https://dev.bancocajasocialsa.org,http://localhost:3000';
