import {
  DaneCodeEnum,
  DocumentRuleResponseDto,
  GenderEnum,
  GovIssueIdentTypeEnum,
  MaritalStatusEnum,
} from '@bcs/types';
export const RESPONSE_LIB_DOCUMENT_EXEMPTION_DOC = {
  status: {
    statusDesc: 'OK',
  },
  responseDetail: {
    errorCode: '',
    errorDesc: '',
    errorType: '',
  },
  govIssueIdent: {
    govIssueIdentType: GovIssueIdentTypeEnum.CITIZENSHIP_CARD,
    identSerialNum: '1234567890',
    expDt: undefined,
    issueLoc: undefined,
    gender: undefined,
    birthDt: undefined,
    country: undefined,
  },
  depAcctStmtRec: {
    depAcctId: {
      refNumber: '01',
      acctId: 'dd',
    },
  },
  offer: {
    subprocessStage: 'string',
    requestType: '01',
    requestVersion: '01',
    processStage: 'dd',
    cityId: DaneCodeEnum.Abrego,
    flagRecommended: 'string',
    indMoment: 'string',
    executionLine: 'string',
  },
  applicantInfo: {
    sarlaftDate: 'string',
    flagDiscount: 'string',
    amtDesc: 'string',
    leafletType: 'string',
    govIssueIdent: {
      govIssueIdentType: GovIssueIdentTypeEnum.CITIZENSHIP_CARD,
      identSerialNum: '1234567890',
      expDt: '',
      issueLoc: DaneCodeEnum.Abrego,
      gender: GenderEnum.M,
      birthDt: new Date(),
      country: 'string',
    },
    personName: {
      lastName: 'string',
      secondLastName: 'string',
      firstName: 'string',
      middleName: 'string',
      fullName: 'string',
    },
    rentalAmt: 'string',
    mainHolder: 'string',
    flagNoCustomerPresence: 'string',
    entprBusiness: {
      entprDesc: 'string',
      entprType: 'string',
      strategyType: 'string',
      strategyId: 'string',
    },
    personInfo: {
      age: 'string',
      birthDt: 'string',
      typeOfHousing: 'string',
      educationLevel: 'string',
      gender: GenderEnum.M,
      maritalStatus: MaritalStatusEnum.C,
      govIssueIdent: {
        govIssueIdentType: GovIssueIdentTypeEnum.CITIZENSHIP_CARD,
        identSerialNum: '1234567890',
        expDt: '',
        issueLoc: DaneCodeEnum.Abrego,
        gender: GenderEnum.M,
        birthDt: new Date(),
        country: 'string',
      },
      deceaseCert: 'string',
      deceaseDt: 'string',
      dependantQty: 'string',
      indBiometricValidation: 'string',
    },
    mortagageInfo: {
      housingType: 'string',
    },
    flagEmployeeFS: 'string',
    fsEmploymentType: 'string',
    flagIncomeValidation: 'Y',
  },
};

export const RESPONSE_LIB_DOCUMENT_RULE_DOC: DocumentRuleResponseDto = {
  responseType: {
    value: undefined,
  },
  responseDetail: {
    errorCode: '',
    errorDesc: '',
    errorType: '',
  },
  listOrderRS: [
    {
      catalogueInfo: {
        numberOrder: '1',
        orderType: undefined,
        orderReview: undefined,
      },
    },
  ],
  listDocument: [
    {
      documentInfo: {
        codeDocRequired: '1',
        nameDocument: '1',
        nameSegment: '1',
        incomeSegment: '1',
        certifiesSegment: '1',
        govIssueIdent: {
          identSerialNum: '1234567890',
          govIssueIdentType: GovIssueIdentTypeEnum.CITIZENSHIP_CARD,
          issueLoc: undefined,
          gender: undefined,
          birthDt: undefined,
          country: undefined,
          cityId: undefined,
        },
        product: {
          itemGeneric1: undefined,
          itemGeneric2: undefined,
          idPortfolioLine: undefined,
          priority: undefined,
          flagPortfolioBuy: undefined,
          productNumber: undefined,
          indCollectBalance: undefined,
          duality: undefined,
          idIncrementQuota: undefined,
          productType: '300121',
          currentQuota: undefined,
          additionalQuota: undefined,
          productMaxAmt: undefined,
          estimateAmt: undefined,
          amtRequestedSourceOrder: undefined,
          productTA: undefined,
          campaignId: undefined,
          amtRequested: null,
          flagIncrementQuota: undefined,
          exception: undefined,
          vlrExcess: undefined,
          exemptionAmt: undefined,
          flagSelectedOffered: undefined,
          aliasName: undefined,
          category: undefined,
          groupingCodeId: undefined,
          descProduct: undefined,
          nameProduct: undefined,
          manufacturerProduct: undefined,
          productId: undefined,
          productClass: undefined,
          productLine: undefined,
          flagSelected: undefined,
          channelSales: undefined,
          amt: undefined,
          idProduct: undefined,
          idIntegration: undefined,
          flagProductSelected: undefined,
          nameProductSIEBEL: undefined,
          desc: undefined,
          flagMVCollectBalance: undefined,
          extendedDiscount: undefined,
          othersDiscounts: undefined,
          numPin: undefined,
          amortisationSystem: undefined,
          flagCreditOwnAccount: undefined,
          flagCreditCHFAccount: undefined,
          termUnits: undefined,
          payPeriodicityId: undefined,
          curRate: undefined,
          idViability: undefined,
          productStatus: undefined,
          causeAmountDecrease: undefined,
          administrationSystem: undefined,
          productSurplus: undefined,
          flagDiscounts: undefined,
        },
        depAcctId: {
          refNumber: null,
          acctId: '1',
        },
        exceptionGrounds: '1',
      },
    },
  ],
  listGroupDocuments: [
    {
      code: '1',
      description: '1',
      minimumRequired: '1',
      documentInfo: {
        codeProcess: '1',
        sendingFormat: '1',
        productId: {
          ledgerCode: '1',
          subLedgerCode: '1',
          groupCode: '1',
          ledger: undefined,
          subLedger: undefined,
          group: undefined,
          nameGroup: undefined,
          macroProduct: undefined,
        },
        codeSegment: '1',
        exists: '1',
        obligation: '1',
        origen: '1',
        uploadDocumentManager: '1',
        participant: '1',
        action: '1',
        product: {
          productType: '1',
          amtRequested: '1',
        },
        stage: '1',
        code: '1',
        codeClassRev: '1',
        revisionCode: '1',
        digitizeOffice: '1',
        flag: '1',
        format: '1',
        listProperty: [
          {
            property: {
              code: '1',
              desc: '1',
              status: '1',
              name: '1',
              value: '1',
              indicator: '1',
            },
          },
        ],
        signatureRequired: '1',
        footprintRequired: '1',
        type: '1',
        typeDocumentary: '1',
        documentValidity: '1',
        documentaryTypeDescription: '1',
        listDocumentValidations: [
          {
            valid: {
              code: '1',
              description: '1',
              status: '1',
              name: '1',
              value: '1',
              indicator: '1',
            },
            validity: {
              code: '1',
              description: '1',
              status: '1',
              name: '1',
              value: '1',
              indicator: '1',
            },
            observations: '1',
            code: '1',
            idType: '1',
            description: '1',
          },
        ],
        documentCondition: '1',
        requested: '1',
        indClientValid: '1',
        destinationCredit: '1',
        businessInfo: {
          labourContractType: undefined,
          flagMainJobActivity: undefined,
          subSegment: undefined,
          formality: undefined,
          incomeContribution: undefined,
          applicantMarket: undefined,
          flagSegment: undefined,
          rentType: undefined,
          netIncomeAmt: undefined,
          discountCapacity: undefined,
          incomeAmt: undefined,
          jobYears: undefined,
          jobMonths: undefined,
          segment: undefined,
          businessType: undefined,
          ocupation: '1',
          businessType2: undefined,
          businessType3: undefined,
          businessType4: undefined,
          businessType5: undefined,
          ocupationId: undefined,
          formality2: undefined,
          applicantMarket2: undefined,
          ocupationId2: undefined,
          segment2: undefined,
          subSegment2: undefined,
          formality3: undefined,
          applicantMarket3: undefined,
          ocupationId3: undefined,
          segment3: undefined,
          subSegment3: undefined,
          formality4: undefined,
          applicantMarket4: undefined,
          ocupationId4: undefined,
          segment4: undefined,
          subSegment4: undefined,
          formality5: undefined,
          applicantMarket5: undefined,
          ocupationId5: undefined,
          segment5: undefined,
          subSegment5: undefined,
          questionData: undefined,
          labourSector: undefined,
          idItem: undefined,
          labourContracType: undefined,
          flagTransportSector: undefined,
          idCompanyPerson: undefined,
          nameCompanyPerson: undefined,
          flagWorkSite: undefined,
          contractId: undefined,
          labourContract: undefined,
        },
      },
    },
  ],
  listRsAdvisorContact: [
    {
      adviser: {
        idContact: '1',
        adviserContactStatus: '1',
        adviserType: '1',
        processCode: '1',
        stageCode: '1',
      },
    },
  ],
};
export const SAVE_DOCUMENTS_REQUEST = {
  property: [
    {
      value: 'CC',
      name: 'xTipoID',
    },
    {
      value: '1084898827',
      name: 'xNumeroID',
    },
    {
      value: 'T0131',
      name: 'xTipoDocumento',
    },
    {
      value: '13/08/2018',
      name: 'xFechaExpedicion',
    },
    {
      value: '9999',
      name: 'xCodigoOficina',
    },
  ],
  file: {
    documentName: '1234758',
    fileId: '24865',
    fileType: 'Document',
    fileTittle: 'T0706CC1084898827',
    fileName: 'T0706CC1084898827.pdf',
    fileBase64: 'JVBERi0xLjYNCjUgMCBvYmoNCjw8DQov',
    fileSecurityGroup: 'Public',
    fileCreationUser: 'G637TEMS',
    fileStageCode: '07',
    fileProcessCode: '03',
  },
  depAcctStmtRec: {
    product: {
      acctId: '',
      product: {
        productType: 'AHORROS',
        productId: 'Cuenta Amiga',
        acctId: '24026781578',
        handlingType: 'Plastico',
        handlingId: '2254670145980109',
      },
    },
  },
  product: {
    productId: {
      group: '1',
      subLeger: '4',
      ledger: '3',
    },
  },
};

export const SAVE_DOCUMENTS_RESPONSE = {
  file: {
    fileId: '497709',
    revisionClassId: '489008',
    revisionId: '1',
    revisionTag: '1',
  },
};
